### ISSUE TITLE
[dev] register a new account with a existing email (legion 7.x bnet)

### ISSUE THREAD

**Issue by Aszune** [fixcore/BlizzCMS#199]
**Description:**

The register system for bnet, not detect existing email in existing account, when register a new account.

**Current behaviour:**

If I try create new account with existing "username", the system show me notification about it. That's correct.

But, if I try a register new account with a new "username" but I put already existing "email", the account is created but unusable, for obviously reasons, in legion your login user it's email, and in this case exists 2 account with the same email and only one account works to login.

Some screens, same email in account 13 and 14, only account with id 13 can login with the email and password:

![accountdoble](https://user-images.githubusercontent.com/4223661/35414625-47af0702-0223-11e8-9427-8697a23fd47e.jpg)

![accountdoble2](https://user-images.githubusercontent.com/4223661/35414650-54f0fc18-0223-11e8-99e5-8375aaa34eb6.jpg)

A small suggestion: Make the notification more visible and understandable. Specify if the account could not be registered by existing "username" or by existing "email".

![accountalreadyexistmessage](https://user-images.githubusercontent.com/4223661/35411336-b09e4ca6-0218-11e8-8c73-a71f7095ecf4.jpg)

**Branch(es):**

branch: devs
commit: https://github.com/fixcore/BlizzCMS/commit/13761afc67e3e7df54ce0afea70f64358ff89421

**Comment by fixcore** [comment]
Fixed, please confirm me

**Comment by Aszune** [comment]
Hm, not fixed.

Now the account is not created and I see the following error:

> An uncaught Exception was encountered
> 
> Type: Error
> 
> Message: Call to undefined method M_data::getSpecifyEmail()
> 
> Filename: D:\Programas\xampp\htdocs\blizzcms\application\modules\user\views\register.php
> 
> Line Number: 34
> 
> Backtrace:
> 
> File: D:\Programas\xampp\htdocs\blizzcms\application\third_party\MX\Loader.php
> Line: 357
> Function: include
> 
> File: D:\Programas\xampp\htdocs\blizzcms\application\third_party\MX\Loader.php
> Line: 300
> Function: _ci_load
> 
> File: D:\Programas\xampp\htdocs\blizzcms\application\modules\user\controllers\User.php
> Line: 144
> Function: view
> 
> File: D:\Programas\xampp\htdocs\blizzcms\index.php
> Line: 315
> Function: require_once

I use the latest commit in dev branch: https://github.com/fixcore/BlizzCMS/commit/8060abf40f98ee03b56bfdbdc4272333bdfe0e6b

**Comment by fixcore** [comment]
Fixed, please confirm me

**Comment by Aszune** [comment]
Fixed 👍🏼
Now the register module, works as intented :D

Thanks!!
