### ISSUE TITLE
[dev] Empty forum replies should not get posted

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#236]
**Description:**
Right now you can post empty replies so it looks like this:

![posting](https://user-images.githubusercontent.com/18347559/35742420-afd87ac6-083a-11e8-8f3b-ce19cda32272.png)

**Comment by fixcore** [comment]
Fixed, please confirm me.

**Comment by Ovahlord** [comment]
Not fixed. Issue is still there:
![bug](https://user-images.githubusercontent.com/18347559/35854014-6d76abb0-0b2f-11e8-9c25-de339819fa05.png)

**Comment by Ovahlord** [comment]
Did some new tests:
- posting empty replies wont happen anymore, that is fixed.
- posting empty topics still works

**Comment by cavaclub** [comment]
confirm that still possible with title
http://storage1.static.itmages.com/i/18/0220/h_1519129658_8729634_7d8be749d6.png
